"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MapPin, MessageCircle, Package, Search, Ship, Star } from "lucide-react";

type Data = any;
export default function CommercialPortalRenderer({slug}:{slug?:string}){
 const [data,setData]=useState<Data>(null); const [error,setError]=useState("");
 useEffect(()=>{fetch(`/api/public/commercial-portal/config${slug?`?slug=${encodeURIComponent(slug)}`:""}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error||"No disponible");return r.json()}).then(setData).catch(e=>setError(e.message))},[slug]);
 if(error)return <main className="grid min-h-screen place-items-center bg-slate-950 p-6 text-white"><div className="max-w-xl text-center"><h1 className="text-3xl font-black">Portal no configurado</h1><p className="mt-3 text-slate-300">{error}</p></div></main>;
 if(!data)return <main className="grid min-h-screen place-items-center bg-slate-950 text-white"><div className="font-black">Cargando portal...</div></main>;
 const {store,settings:s,services,promotions,faqs,testimonials}=data; const primary=store.primary_color||"#0b1f4d"; const secondary=store.secondary_color||"#0ea5e9";
 return <main className="min-h-screen bg-white text-slate-950">
  {s?.announcement_enabled&&s.announcement_text&&<div className="px-4 py-3 text-center text-sm font-black text-white" style={{backgroundColor:secondary}}>{s.announcement_text}</div>}
  <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="flex items-center gap-3">{store.logo_url?<img src={store.logo_url} alt={store.name} className="h-11 w-11 rounded-2xl object-contain"/>:<div className="grid h-11 w-11 place-items-center rounded-2xl text-white" style={{backgroundColor:primary}}><Package/></div>}<span className="text-xl font-black">{store.name}</span></Link><nav className="hidden gap-6 font-bold text-slate-600 md:flex"><a href="#servicios">Servicios</a><a href="#cotizador">Cotizar</a><Link href="/rastrear">Rastrear</Link><a href="#contacto">Contacto</a></nav><Link href="/login" className="rounded-2xl px-4 py-2 font-black text-white" style={{backgroundColor:primary}}>Acceso</Link></div></header>
  <section className="overflow-hidden px-5 py-16 text-white md:py-24" style={{background:`linear-gradient(135deg,${primary},${secondary})`}}><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><div className="mb-5 inline-flex rounded-full bg-white/15 px-4 py-2 text-sm font-black uppercase tracking-widest">{s?.hero_badge}</div><h1 className="text-4xl font-black leading-tight md:text-6xl">{s?.hero_title}</h1><p className="mt-6 max-w-2xl text-lg font-medium text-white/80 md:text-xl">{s?.hero_subtitle}</p><div className="mt-8 flex flex-wrap gap-3"><a href={s?.hero_primary_href||"#cotizador"} className="rounded-2xl bg-white px-6 py-4 font-black" style={{color:primary}}>{s?.hero_primary_label||"Cotizar ahora"}</a><a href={s?.hero_secondary_href||"/rastrear"} className="rounded-2xl border border-white/40 bg-white/10 px-6 py-4 font-black">{s?.hero_secondary_label||"Rastrear"}</a></div></div><div className="rounded-[36px] border border-white/20 bg-white/10 p-6 shadow-2xl backdrop-blur"><div className="rounded-[28px] bg-white p-6 text-slate-950"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-100 p-3 text-emerald-700"><CheckCircle2/></div><div><p className="text-sm font-bold text-slate-500">Todo desde un solo lugar</p><h2 className="text-2xl font-black">Cotiza · Rastrea · Compra</h2></div></div><div className="mt-6 grid gap-3"><div className="rounded-2xl bg-slate-50 p-4 font-bold"><Ship className="mb-2"/>Opciones aéreas y marítimas</div><div className="rounded-2xl bg-slate-50 p-4 font-bold"><Search className="mb-2"/>Seguimiento claro del envío</div><div className="rounded-2xl bg-slate-50 p-4 font-bold"><MessageCircle className="mb-2"/>Atención directa por WhatsApp</div></div></div></div></div></section>
  {s?.services_section_enabled&&<section id="servicios" className="px-5 py-20"><div className="mx-auto max-w-7xl"><p className="font-black uppercase tracking-widest" style={{color:secondary}}>Nuestros servicios</p><h2 className="mt-2 text-3xl font-black md:text-5xl">Todo lo que tus clientes necesitan</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((x:any)=><article key={x.id} className="rounded-[28px] border border-slate-200 p-6 shadow-sm"><div className="mb-5 grid h-12 w-12 place-items-center rounded-2xl text-white" style={{backgroundColor:primary}}><Package/></div><h3 className="text-xl font-black">{x.title}</h3><p className="mt-3 font-medium leading-7 text-slate-600">{x.description}</p></article>)}</div></div></section>}
  {s?.quote_section_enabled&&<section id="cotizador" className="bg-slate-950 px-5 py-20 text-white"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[36px] border border-white/10 bg-white/5 p-8 md:flex-row md:items-center md:p-12"><div><p className="font-black uppercase tracking-widest text-blue-300">Cotización transparente</p><h2 className="mt-2 text-3xl font-black md:text-5xl">Calcula tu envío en segundos</h2><p className="mt-4 max-w-2xl text-lg text-slate-300">Los precios, mínimos, destinos y métodos se administran desde el panel de cada empresa.</p></div><Link href="/cotizar" className="flex items-center gap-2 rounded-2xl bg-emerald-500 px-6 py-4 font-black text-slate-950">Abrir cotizador <ArrowRight/></Link></div></section>}
  {s?.promotions_section_enabled&&promotions.length>0&&<section className="px-5 py-20"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black md:text-5xl">Promociones activas</h2><div className="mt-9 grid gap-5 md:grid-cols-2">{promotions.map((x:any)=><article key={x.id} className="rounded-[30px] p-7 text-white" style={{background:`linear-gradient(135deg,${primary},${secondary})`}}><span className="rounded-full bg-white/20 px-3 py-1 text-xs font-black">{x.badge||"Promoción"}</span><h3 className="mt-5 text-2xl font-black">{x.title}</h3><p className="mt-3 text-white/80">{x.description}</p>{x.button_href&&<a href={x.button_href} className="mt-6 inline-flex rounded-xl bg-white px-4 py-2 font-black" style={{color:primary}}>{x.button_label||"Ver más"}</a>}</article>)}</div></div></section>}
  {s?.testimonials_section_enabled&&testimonials.length>0&&<section className="bg-slate-50 px-5 py-20"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black md:text-5xl">Lo que dicen nuestros clientes</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{testimonials.map((x:any)=><article key={x.id} className="rounded-[28px] bg-white p-6 shadow-sm"><div className="flex gap-1 text-amber-500">{Array.from({length:x.rating||5}).map((_,i)=><Star key={i} size={18} fill="currentColor"/>)}</div><p className="mt-4 font-medium leading-7 text-slate-600">“{x.testimonial}”</p><p className="mt-5 font-black">{x.customer_name}</p><p className="text-sm text-slate-500">{x.customer_detail}</p></article>)}</div></div></section>}
  {s?.faq_section_enabled&&faqs.length>0&&<section className="px-5 py-20"><div className="mx-auto max-w-4xl"><h2 className="text-center text-3xl font-black md:text-5xl">Preguntas frecuentes</h2><div className="mt-9 space-y-4">{faqs.map((x:any)=><details key={x.id} className="rounded-2xl border border-slate-200 p-5"><summary className="cursor-pointer text-lg font-black">{x.question}</summary><p className="mt-3 leading-7 text-slate-600">{x.answer}</p></details>)}</div></div></section>}
  {s?.contact_section_enabled&&<footer id="contacto" className="px-5 py-16 text-white" style={{backgroundColor:primary}}><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><h2 className="text-3xl font-black">{store.name}</h2><p className="mt-4 max-w-xl text-white/70">{s.footer_text||"Estamos listos para ayudarte con tu próximo envío."}</p></div><div className="space-y-3 font-bold">{s.address&&<p className="flex gap-2"><MapPin/>{s.address}</p>}{s.phone&&<p>{s.phone}</p>}{s.email&&<p>{s.email}</p>}{s.business_hours&&<p>{s.business_hours}</p>}{s.whatsapp_phone&&<a className="inline-flex items-center gap-2 rounded-2xl bg-emerald-500 px-5 py-3 text-slate-950" href={`https://wa.me/${String(s.whatsapp_phone).replace(/\D/g,"")}`}><MessageCircle/>WhatsApp</a>}</div></div></footer>}
 </main>
}
