"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BarChart3, Clock3, Loader2, MapPin, RefreshCw, Search, Truck } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useStore } from "@/hooks/useStore";
import { useAdminAccess } from "@/hooks/useAdminAccess";

type Zone={id:string;name:string;color:string|null;is_active:boolean};
type Row={id:string;request_code:string;customer_name:string;phone:string;city:string;address_line_1:string;postal_code:string;package_count:number;estimated_weight:number|null;status:string;created_at:string;assigned_zone_id:string|null;suggested_zone_id:string|null;preferred_dates:string[];zone:Zone|null};
const blocked=new Set(["assigned","en_route","picked_up","cancelled"]);
const age=(iso:string)=>Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/86400000));

export default function PickupsAdminPage(){
 const {store:selectedStore,loading:storeLoading}=useStore() as any; const {store:accessStore,isSuperAdmin,loading:accessLoading}=useAdminAccess(); const store=isSuperAdmin?selectedStore||accessStore:accessStore;
 const [rows,setRows]=useState<Row[]>([]),[zones,setZones]=useState<Zone[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[zoneFilter,setZoneFilter]=useState("all"),[selected,setSelected]=useState<string[]>([]);
 async function authHeaders(){const {data}=await supabase.auth.getSession();return {Authorization:`Bearer ${data.session?.access_token||""}`};}
 async function load(){if(!store?.id)return;setLoading(true);setError("");const r=await fetch(`/api/admin/pickups/planning?store_id=${store.id}`,{headers:await authHeaders(),cache:"no-store"});const j=await r.json();if(!r.ok)setError(j.error||"No se pudo cargar.");else{setRows(j.requests||[]);setZones(j.zones||[])}setLoading(false)}
 useEffect(()=>{load()},[store?.id]);
 const pending=rows.filter(r=>!blocked.has(r.status));
 const demand=useMemo(()=>{const map=new Map<string,{zone:Zone|null,count:number,packages:number,weight:number,oldest:number,cities:Map<string,number>}>();for(const r of pending){const key=r.zone?.id||"unassigned";if(!map.has(key))map.set(key,{zone:r.zone,count:0,packages:0,weight:0,oldest:0,cities:new Map()});const x=map.get(key)!;x.count++;x.packages+=r.package_count||0;x.weight+=Number(r.estimated_weight||0);x.oldest=Math.max(x.oldest,age(r.created_at));x.cities.set(r.city,(x.cities.get(r.city)||0)+1)}return [...map.values()].sort((a,b)=>b.count-a.count)},[rows]);
 const filtered=pending.filter(r=>(zoneFilter==="all"||(zoneFilter==="unassigned"?!r.zone:r.zone?.id===zoneFilter))&&`${r.customer_name} ${r.city} ${r.request_code} ${r.phone}`.toLowerCase().includes(search.toLowerCase()));
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 async function assign(zoneId:string){if(!selected.length)return;const r=await fetch("/api/admin/pickups/planning",{method:"PATCH",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify({store_id:store.id,request_ids:selected,assigned_zone_id:zoneId||null})});const j=await r.json();if(!r.ok)return setError(j.error);setSelected([]);load()}
 if(accessLoading||storeLoading||loading)return <div className="p-12 text-center"><Loader2 className="mx-auto animate-spin"/></div>;
 return <div className="space-y-6">
  <header className="rounded-[2rem] bg-[#071d43] p-7 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-200">Planificación por demanda</p><div className="mt-2 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black">Demanda de recogidas</h1><p className="mt-2 text-blue-100">Las zonas agrupan solicitudes. Tú decides qué zona visitar y en qué fecha.</p></div><div className="flex gap-2"><Link href="/admin/pickups/routes" className="rounded-xl border border-white/20 px-4 py-3 font-black">Ver rutas</Link><button onClick={load} className="rounded-xl bg-white px-4 py-3 font-black text-[#071d43]"><RefreshCw className="inline mr-2" size={17}/>Actualizar</button></div></div></header>
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{demand.map((d,i)=><button key={d.zone?.id||"none"} onClick={()=>setZoneFilter(d.zone?.id||"unassigned")} className="rounded-[1.6rem] border bg-white p-5 text-left shadow-sm hover:shadow-md"><div className="flex items-center justify-between"><span className="h-3 w-3 rounded-full" style={{background:d.zone?.color||"#94a3b8"}}/><span className="text-xs font-black text-slate-400">{d.oldest} días máx.</span></div><h2 className="mt-3 text-xl font-black">{d.zone?.name||"Sin zona"}</h2><p className="mt-1 text-4xl font-black">{d.count}</p><p className="text-sm font-bold text-slate-500">solicitudes · {d.packages} paquetes</p><p className="mt-3 truncate text-xs font-bold text-slate-500">{[...d.cities.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([c,n])=>`${c} ${n}`).join(" · ")}</p></button>)}</section>
  <section className="grid gap-3 rounded-[1.5rem] border bg-white p-4 md:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="h-12 w-full rounded-xl border pl-11 pr-3 font-bold" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, ciudad o código..."/></label><select className="h-12 rounded-xl border px-3 font-black" value={zoneFilter} onChange={e=>setZoneFilter(e.target.value)}><option value="all">Todas las zonas</option><option value="unassigned">Sin zona</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></section>
  {selected.length>0&&<div className="sticky top-3 z-20 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#071d43] p-4 text-white shadow-xl"><b>{selected.length} seleccionadas</b><div className="flex flex-wrap gap-2"><select onChange={e=>assign(e.target.value)} defaultValue="" className="rounded-xl bg-white px-3 py-2 font-black text-slate-900"><option value="" disabled>Asignar zona...</option><option value="">Sin zona</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select><Link href={`/admin/pickups/routes/new?requests=${selected.join(",")}`} className="rounded-xl bg-white px-4 py-2 font-black text-[#071d43]">Preparar ruta</Link><button onClick={()=>setSelected([])} className="rounded-xl border border-white/20 px-4 py-2 font-black">Cancelar</button></div></div>}
  {error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}
  <div className="grid gap-4 xl:grid-cols-2">{filtered.map(r=><article key={r.id} className={`rounded-[1.5rem] border bg-white p-5 shadow-sm ${selected.includes(r.id)?"ring-2 ring-blue-400":""}`}><div className="flex gap-3"><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>toggle(r.id)} className="mt-1 h-5 w-5"/><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">{r.request_code}</span><span className="rounded-full px-3 py-1 text-xs font-black" style={{background:`${r.zone?.color||"#94a3b8"}22`,color:r.zone?.color||"#475569"}}>{r.zone?.name||"Sin zona"}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-700"><Clock3 size={12} className="inline mr-1"/>{age(r.created_at)} días</span></div><h2 className="mt-3 text-lg font-black">{r.customer_name}</h2><p className="mt-1 text-sm font-bold text-slate-600"><MapPin size={15} className="inline mr-1 text-red-500"/>{r.address_line_1}, {r.city} {r.postal_code}</p><p className="mt-3 text-sm font-bold text-slate-500">{r.package_count} paquete(s){r.estimated_weight?` · ${r.estimated_weight} lb`:""}</p></div></div></article>)}</div>
 </div>
}
