"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Building2, CalendarDays, LayoutList, Loader2, MapPin, Search, Truck } from "lucide-react";
import { useStore } from "@/hooks/useStore";
import { useAdminAccess } from "@/hooks/useAdminAccess";
import { getPickupRequests, getPickupZones, updatePickupRequestStatus } from "@/lib/services/pickups";
import { PICKUP_STATUS_LABELS, type PickupRequest, type PickupRequestStatus, type PickupZone } from "@/lib/pickups/types";

type ViewMode = "list" | "city" | "zone";
export default function PickupsAdminPage(){
 const {store:selectedStore,loading:storeLoading}=useStore() as any; const {store:accessStore,isSuperAdmin,loading:accessLoading}=useAdminAccess(); const store=isSuperAdmin?selectedStore||accessStore:accessStore;
 const [requests,setRequests]=useState<PickupRequest[]>([]); const [zones,setZones]=useState<PickupZone[]>([]); const [loading,setLoading]=useState(true); const [view,setView]=useState<ViewMode>("zone"); const [search,setSearch]=useState("");
 async function load(){if(!store?.id)return;setLoading(true);const [r,z]=await Promise.all([getPickupRequests(store.id),getPickupZones(store.id)]);setRequests(r.data);setZones(z.data as PickupZone[]);setLoading(false)}
 useEffect(()=>{load()},[store?.id]);
 const zoneMap=useMemo(()=>new Map(zones.map(z=>[z.id,z])),[zones]);
 const filtered=useMemo(()=>requests.filter(r=>`${r.customer_name} ${r.city} ${r.request_code}`.toLowerCase().includes(search.toLowerCase())),[requests,search]);
 const groupedCity=useMemo(()=>filtered.reduce<Record<string,PickupRequest[]>>((a,r)=>{(a[r.city]||=[]).push(r);return a},{}),[filtered]);
 const groupedZone=useMemo(()=>filtered.reduce<Record<string,PickupRequest[]>>((a,r)=>{const id=r.assigned_zone_id||r.suggested_zone_id||"unassigned";(a[id]||=[]).push(r);return a},{}),[filtered]);
 if(accessLoading||storeLoading||loading)return <div className="p-12 text-center"><Loader2 className="mx-auto animate-spin"/></div>;
 return <div className="space-y-6">
  <header className="rounded-[2rem] bg-[#071d43] p-7 text-white"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-200">Demanda operativa</p><h1 className="mt-2 text-3xl font-black">Solicitudes de recogida</h1><p className="mt-2 text-blue-100/75">Analiza la demanda por zona, ciudad y fechas preferidas antes de construir la ruta.</p></div><div className="flex gap-2"><Link href="/admin/pickups/zones" className="rounded-2xl bg-white/10 px-4 py-3 font-black">Configurar zonas</Link><Link href="/admin/pickups/routes/new" className="rounded-2xl bg-white px-4 py-3 font-black text-[#071d43]">Crear ruta</Link></div></div></header>
  <section className="flex flex-col gap-3 rounded-2xl border bg-white p-4 md:flex-row md:items-center md:justify-between"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, ciudad o código..." className="h-12 w-full rounded-2xl border pl-11 pr-4 font-bold"/></label><div className="flex rounded-2xl bg-slate-100 p-1">{([["zone","Por zona",Building2],["city","Por ciudad",MapPin],["list","Lista",LayoutList]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={`flex items-center gap-2 rounded-xl px-4 py-2 font-black ${view===id?"bg-white shadow":"text-slate-500"}`}><Icon size={16}/>{label}</button>)}</div></section>
  {view==="zone"&&<div className="grid gap-5 xl:grid-cols-2">{Object.entries(groupedZone).map(([zoneId,items])=>{const zone=zoneMap.get(zoneId);const dates=countDates(items);const cities=[...new Set(items.map(i=>i.city))];return <article key={zoneId} className="rounded-[1.8rem] border bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-blue-600">Zona operativa</p><h2 className="mt-1 text-2xl font-black">{zone?.name||"Sin zona asignada"}</h2></div><span className="rounded-2xl bg-blue-50 px-4 py-2 text-xl font-black text-blue-700">{items.length}</span></div><div className="mt-4 flex flex-wrap gap-2">{cities.map(c=><span key={c} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{c}</span>)}</div><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-slate-400">Fechas con mayor demanda</p>{dates.slice(0,3).map(([d,n])=><div key={d} className="mt-2 flex justify-between font-bold"><span>{formatDate(d)}</span><span>{n} solicitudes</span></div>)}</div><Link href={`/admin/pickups/routes/new?zone=${zoneId}`} className="mt-5 block rounded-2xl bg-[#071d43] px-4 py-3 text-center font-black text-white">Crear ruta para esta zona</Link></article>})}</div>}
  {view==="city"&&<div className="grid gap-4 xl:grid-cols-3">{Object.entries(groupedCity).map(([city,items])=><article key={city} className="rounded-[1.5rem] border bg-white p-5"><h2 className="text-xl font-black">{city}</h2><p className="mt-1 text-sm text-slate-500">{items.length} solicitudes</p><div className="mt-4 space-y-2">{countDates(items).slice(0,3).map(([d,n])=><div key={d} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm font-bold"><span>{formatDate(d)}</span><span>{n}</span></div>)}</div></article>)}</div>}
  {view==="list"&&<div className="grid gap-4 xl:grid-cols-2">{filtered.map(item=><article key={item.id} className="rounded-[1.5rem] border bg-white p-5"><div className="flex justify-between gap-4"><div><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-black text-blue-700">{item.request_code}</span><h2 className="mt-3 text-xl font-black">{item.customer_name}</h2><p className="mt-1 text-sm font-bold text-slate-500">{item.city} · {zoneMap.get(item.assigned_zone_id||item.suggested_zone_id||"")?.name||"Sin zona"}</p><p className="mt-2 flex items-center gap-1 text-xs font-black text-blue-700"><CalendarDays size={14}/>{(item.preferred_dates||[]).map(formatDate).join(" · ")||"Flexible"}</p></div><select value={item.status} onChange={async e=>{const status=e.target.value as PickupRequestStatus;await updatePickupRequestStatus(item.store_id,item.id,status);setRequests(r=>r.map(x=>x.id===item.id?{...x,status}:x))}} className="h-11 rounded-xl border px-3 font-bold">{Object.entries(PICKUP_STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></article>)}</div>}
 </div>
}
function countDates(items:PickupRequest[]){const m=new Map<string,number>();items.forEach(i=>(i.preferred_dates||[]).forEach(d=>m.set(d,(m.get(d)||0)+1)));return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function formatDate(v:string){return new Intl.DateTimeFormat("es-US",{weekday:"short",day:"numeric",month:"short"}).format(new Date(`${v}T12:00:00`))}
